package com.albonik.vpn

import android.content.Context
import android.content.res.Resources
import java.io.BufferedReader
import java.io.InputStreamReader

/**
 * VPN Asset Loader for Play Store App Bundle compatibility
 * Handles dual-path loading for different build types
 */
class VpnAssetLoader(private val context: Context) {
    
    /**
     * Load VPN configuration with fallback paths
     * Critical for App Bundle release where asset paths may change
     */
    fun loadVpnConfig(configName: String = "client.ovpn"): String {
        return try {
            // 1. Try Flutter assets first (development/debug builds)
            loadFromFlutterAssets(configName)
        } catch (e: Exception) {
            try {
                // 2. Fallback to Android raw resources (Play Store bundles)
                loadFromRawResources(configName)
            } catch (e2: Exception) {
                // 3. Return basic config as last resort
                createBasicConfig()
            }
        }
    }
    
    /**
     * Load from Flutter assets directory
     */
    private fun loadFromFlutterAssets(configName: String): String {
        return context.assets.open("flutter_assets/assets/$configName").use { inputStream ->
            BufferedReader(InputStreamReader(inputStream)).use { reader ->
                reader.readText()
            }
        }
    }
    
    /**
     * Load from Android raw resources (Play Store compatible)
     */
    private fun loadFromRawResources(configName: String): String {
        val resourceName = configName.replace(".ovpn", "").replace(".", "_")
        val resourceId = context.resources.getIdentifier(
            resourceName, 
            "raw", 
            context.packageName
        )
        
        if (resourceId == 0) {
            throw Resources.NotFoundException("Raw resource not found: $resourceName")
        }
        
        return context.resources.openRawResource(resourceId).use { inputStream ->
            BufferedReader(InputStreamReader(inputStream)).use { reader ->
                reader.readText()
            }
        }
    }
    
    /**
     * Create basic OpenVPN config as fallback
     */
    private fun createBasicConfig(): String {
        return """
            client
            dev tun
            proto udp
            remote 1.1.1.1 1194
            resolv-retry infinite
            nobind
            persist-key
            persist-tun
            verb 1
            pull
            route-method exe
            route-delay 2
            cipher AES-256-CBC
            auth SHA256
            compress lz4-v2
            fast-io
            script-security 2
            redirect-gateway def1 bypass-dhcp
            dhcp-option DNS 8.8.8.8
            dhcp-option DNS 8.8.4.4
            auth-user-pass
            auth-nocache
            # Fallback config generated by VpnAssetLoader
        """.trimIndent()
    }
    
    /**
     * Validate VPN configuration
     */
    fun isValidConfig(config: String): Boolean {
        return config.contains("client") && 
               config.contains("remote") && 
               config.contains("dev tun")
    }
}
