// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJkPbXKK4-2fSpzs_pg8DtmC43RuvaFHE',
    appId: '1:548357430334:android:c2dcdd0dc15dc5b323856f',
    messagingSenderId: '548357430334',
    projectId: 'vpn-master-albonik',
    storageBucket: 'vpn-master-albonik.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiTikfnl-LrL0jr-FPjFvBHOEcPIy8joY',
    appId: '1:548357430334:ios:d219a8655dfefa5f23856f',
    messagingSenderId: '548357430334',
    projectId: 'vpn-master-albonik',
    storageBucket: 'vpn-master-albonik.firebasestorage.app',
    androidClientId: '548357430334-hti8camgrn1ttunibub4mfo6oeo4g4db.apps.googleusercontent.com',
    iosClientId: '548357430334-t6ar0mi81tho24hras5d90cj7kk17k6v.apps.googleusercontent.com',
    iosBundleId: 'com.albonik.vpn',
  );

}