// Extended translations for app_localizations.dart
// Copy these into the translation maps in app_localizations.dart

const Map<String, String> extendedEnglishTranslations = {
  // Existing keys... (keep all previous ones)

  // Home Screen - Extended
  'time_expired': 'Time Expired',
  'time_expired_message':
      'Your free connection time has expired. Upgrade to Premium for unlimited VPN access or watch an ad to get more time!',
  'watch_ad_5_min': 'Watch Ad (+5 min)',
  'upgrade_now': 'Upgrade Now',
  'server_details': 'Server Details',
  'server_ip': 'Server IP',
  'status': 'Status',
  'active': 'Active',
  'inactive': 'Inactive',
  'close': 'Close',
  'quick_connect': 'Quick Connect',
  'change_server': 'Change Server',
  'connection_status': 'Connection status',
  'global_locations': 'Global locations',
  'unlock_features': 'Unlock features',
  'app_preferences': 'App preferences',
  'tell_your_friends': 'Tell your friends',
  'leave_a_review': 'Leave a review',
  'app_information': 'App information',
  'secure_fast_private': 'Secure • Fast • Private',
  'secure_fast_reliable': 'Secure • Fast • Reliable',
  'powered_by': 'Powered by',
  'free': 'FREE',
  'upgrade': 'UPGRADE',

  // Server Screen - Extended
  'active_filters': 'Active filters',
  'clear_filters': 'Clear filters',
  'showing_results': 'Showing results',
  'search_query': 'Search query',
  'free_only': 'Free only',
  'premium_filter': 'Premium filter',
  'sort_by': 'Sort by',
  'filter': 'Filter',
  'connect_to_server': 'Connect to Server',
  'requires_premium': 'Requires Premium',
  'get_premium': 'Get Premium',
  'ms': 'ms',
  'online': 'Online',
  'offline': 'Offline',
  'fastest': 'Fastest',
  'nearest': 'Nearest',

  // Premium Screen - Extended
  'ultra_fast_servers': 'Ultra-Fast Servers',
  'access_premium_servers': 'Access to premium high-speed servers worldwide',
  'advanced_security': 'Advanced-Grade Security',
  'advanced_encryption': 'Advanced encryption and security protocols',
  'ad_free_experience': 'Ad-Free Experience',
  'no_interruptions': 'No ads, no interruptions, pure VPN experience',
  'unlimited_devices': 'Unlimited Devices',
  'connect_unlimited_devices':
      'Connect unlimited devices with one subscription',
  'priority_support': '24/7 Priority Support',
  'instant_help': 'Get instant help whenever you need it',
  'premium_locations': 'Premium Locations',
  'exclusive_servers': 'Access to exclusive server locations',
  'choose_your_plan': 'Choose Your Plan',
  'best_value': 'BEST VALUE',
  'most_popular': 'MOST POPULAR',
  'limited_offer': 'LIMITED OFFER',
  'per_month': '/month',
  'per_year': '/year',
  'one_time': 'One Time',
  'save': 'Save',
  'popular': 'POPULAR',
  'select_plan': 'Select Plan',
  'processing': 'Processing...',
  'please_wait': 'Please wait...',
  'purchase_successful': 'Purchase Successful!',
  'purchase_failed': 'Purchase Failed',
  'already_premium': 'You are already a Premium member!',
  'sign_in_required': 'Sign In Required',
  'sign_in_to_purchase':
      'Please sign in with your Google account to purchase Premium.',
  'continue_with_google': 'Continue with Google',
  'later': 'Later',

  // Auth Screen
  'welcome_back': 'Welcome back',
  'create_your_account': 'Create your account',
  'axe_vpn': 'VPN MASTER',
  'sign_in_with_google': 'Sign In with Google',
  'or': 'OR',
  'email': 'Email',
  'password': 'Password',
  'name': 'Name',
  'continue': 'Continue',
  'dont_have_account': 'Don\'t have an account?',
  'already_have_account': 'Already have an account?',
  'forgot_password': 'Forgot Password?',
  'reset_password': 'Reset Password',
  'enter_email': 'Enter your email',
  'enter_password': 'Enter your password',
  'enter_name': 'Enter your name',
  'email_sent': 'Email Sent!',
  'check_inbox': 'Please check your inbox for password reset instructions.',
  'signing_in': 'Signing in...',
  'creating_account': 'Creating account...',
  'email_required': 'Email is required',
  'password_required': 'Password is required',
  'name_required': 'Name is required',
  'invalid_email': 'Please enter a valid email',
  'password_too_short': 'Password must be at least 6 characters',

  // Privacy Policy
  'privacy_policy_title': 'Privacy Policy',
  'last_updated': 'Last updated',
  'information_we_collect': 'Information We Collect',
  'how_we_use_info': 'How We Use Your Information',
  'data_security': 'Data Security',
  'no_logs_policy': 'No-Logs Policy',
  'third_party_services': 'Third-Party Services',
  'your_rights': 'Your Rights',
  'contact_us': 'Contact Us',
  'read_our_privacy_policy': 'Read our privacy policy',

  // Terms of Service
  'terms_title': 'Terms of Service',
  'acceptance_of_terms': 'Acceptance of Terms',
  'service_description': 'Service Description',
  'user_obligations': 'User Obligations',
  'prohibited_activities': 'Prohibited Activities',
  'subscription_billing': 'Subscription and Billing',
  'cancellation_refund': 'Cancellation and Refund Policy',
  'limitation_liability': 'Limitation of Liability',
  'read_our_terms': 'Read our terms',

  // About Screen
  'app_name_full': 'VPN MASTER',
  'app_version': 'App Version',
  'build_number': 'Build Number',
  'developer': 'Developer',
  'quickro': 'Quickro',
  'website': 'Website',
  'facebook': 'Facebook',
  'twitter': 'Twitter',
  'instagram': 'Instagram',
  'app_info_credits': 'App information and credits',
  'developed_by': 'Developed by',
  'all_rights_reserved': 'All rights reserved',

  // Support Screen
  'contact_support_title': 'Contact Support',
  'help_center': 'Help Center',
  'faq': 'Frequently Asked Questions',
  'email_support': 'Email Support',
  'send_email': 'Send Email',
  'live_chat': 'Live Chat',
  'chat_with_us': 'Chat with us',
  'report_bug': 'Report a Bug',
  'suggest_feature': 'Suggest a Feature',
  'get_help': 'Get help with the app',

  // Settings - Extended
  'block_traffic_vpn_disconnects': 'Block traffic when VPN disconnects',
  'connect_auto_on_start': 'Connect automatically on app start',
  'customize_app_appearance': 'Customize app appearance',
  'select_language_preference': 'Select your preferred language',
  'signed_in_as': 'Signed in as',
  'sign_in_google_account': 'Sign in with Google account',
  'view_subscription_history': 'View your subscription history',
  'restore_from_store':
      'Restore previous purchases from Play Store or App Store',
  'manage_push_notifications': 'Manage push notifications',
  'choose_theme': 'Choose Theme',
  'light_mode_desc': 'Light Mode',
  'dark_mode_desc': 'Dark Mode',
  'system_default_desc': 'System Default',
  'choose_protocol': 'Choose Protocol',
  'udp_faster': 'UDP - Faster, less reliable',
  'tcp_slower': 'TCP - Slower, more reliable',
  'choose_color': 'Choose Accent Color',
  'select_accent_color': 'Select your preferred accent color',
  'account_details': 'Account Details',
  'email_verified': 'Email verified',
  'email_not_verified': 'Email not verified',
  'delete_account': 'Delete Account',
  'delete_account_confirm':
      'Are you sure you want to delete your account? This action cannot be undone.',
  'restoring_purchases': 'Restoring purchases...',
  'purchases_restored': 'Purchases Restored!',
  'no_purchases_found': 'No purchases found to restore.',

  // Notifications
  'vpn_connected': 'VPN Connected',
  'vpn_disconnected': 'VPN Disconnected',
  'connected_successfully_to': 'Connected successfully to',
  'connection_lost': 'Connection lost',
  'reconnecting': 'Reconnecting...',
  'tap_to_open': 'Tap to open',

  // Drawers & Navigation
  'menu': 'Menu',
  'rate_us': 'Rate Us',
  'share': 'Share',
  'feedback': 'Feedback',
  'exit': 'Exit',
  'exit_app': 'Exit App',
  'exit_confirm': 'Are you sure you want to exit?',
  'press_again_to_exit': 'Press back again to exit',

  // Errors & Messages
  'something_went_wrong': 'Something went wrong',
  'try_again': 'Try Again',
  'retry': 'Retry',
  'failed_to_load': 'Failed to load',
  'check_connection': 'Please check your internet connection',
  'server_error': 'Server error',
  'timeout_error': 'Connection timeout',
  'unknown_error': 'Unknown error occurred',
  'permission_denied': 'Permission denied',
  'vpn_permission_required': 'VPN permission is required',
  'grant_permission': 'Grant Permission',
  'feature_not_available': 'This feature is not available',
  'coming_soon': 'Coming Soon',
  'under_development': 'This feature is under development',

  // Loading States
  'loading_servers': 'Loading servers...',
  'loading_plans': 'Loading plans...',
  'loading_data': 'Loading data...',
  'please_wait_loading': 'Please wait...',
  'initializing': 'Initializing...',
  'connecting_to_server': 'Connecting to server...',
  'establishing_connection': 'Establishing secure connection...',
  'disconnecting_from_server': 'Disconnecting from server...',

  // Connection Details
  'connection_info': 'Connection Information',
  'connected_since': 'Connected since',
  'data_sent': 'Data Sent',
  'data_received': 'Data Received',
  'session_duration': 'Session Duration',
  'bandwidth_used': 'Bandwidth Used',
  'protocol_used': 'Protocol Used',
  'encryption': 'Encryption',
  'port': 'Port',

  // Misc
  'january': 'January',
  'february': 'February',
  'march': 'March',
  'april': 'April',
  'may': 'May',
  'june': 'June',
  'july': 'July',
  'august': 'August',
  'september': 'September',
  'october': 'October',
  'november': 'November',
  'december': 'December',
  '2025': '2025',
  'maybe_later': 'Maybe Later',
  'rate_now': 'Rate Now',
  'got_it': 'Got It',
  'learn_more': 'Learn More',
  'see_all': 'See All',
  'show_less': 'Show Less',
  'show_more': 'Show More',
  'apply': 'Apply',
  'reset': 'Reset',
  'confirm': 'Confirm',
  'dismiss': 'Dismiss',
};
